In [1]:
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import scipy as sp
import scipy.stats
import pandas as pd
import numpy as np
import random
import pymysql
import datetime

In [2]:
def get_mean_taste():
    conn = pymysql.connect(host = "localhost",
                user= "root", password = "1234", charset = "utf8")
    cursor = conn.cursor()
    cursor.execute("select menu_id, restaurant_id,AVG(flavor) from young_cheline.evaluate group by menu_id, restaurant_id;")
    res = cursor.fetchall()
    return res

In [3]:
def detail_analyze(df):
    
    menu_mean_list = df.iloc[:,2]
    menu_mean_std = np.std(menu_mean_list)
    menu_mean_mean = np.mean(menu_mean_list)
    rv = sp.stats.norm(0,1)
    menu_percent = 1-rv.cdf((menu_mean_list - menu_mean_mean)/menu_mean_std)
    df_data = []
    for i in range(len(menu_percent)):
        df_data.append(round(menu_percent[i]*100,3))
    
    Percent_DeliFood_df = pd.DataFrame(columns = ['상위 N% 맛식'],data = df_data)
    mean = df.iloc[:,[1,2]]
    result = Percent_DeliFood_df
    return result

In [4]:
meandf = pd.DataFrame(data = get_mean_taste())

In [5]:
meandf

     0           1         2
0    1  1883770159  2.013472
1    2    15752650  2.249912
2    3   714569417  1.971009
3    4    11385265  1.949141
4    5   287757696  1.971349
5    6   392495073  2.263122
6    7   392495073  1.798023
7    8    10306127  2.127524
8    9   434788818  2.218496
9   10    20638851  1.833683
10  11  1258680088  2.133357
11  12    27407049  2.193283
12  13    27407036  2.136953
13  14    27407036  1.787889
14  15   444340519  1.936259
15  16    14541884  2.087031
16  17  1566612864  1.770864
17  18   226916996  1.805411
18  19   143343585  2.260931
19  20   880781940  1.937367
20  21   983114429  1.927943
21  22    11300334  1.973775
22  23   746623517  2.117647
23  24  2020305821  2.172218
24  25  2020305821  2.175153
25  26  2020305821  2.147478
26  27    26353366  2.000697
27  28  1956466361  1.998232
28  29  1032781993  1.959879
29  30  1323716207  1.988070
30  31   277055458  2.184971
31  32   777963780  2.292700
32  33  2084958402  2.100732
33  34    86660948  2.163929
34  35  2020305821  2.170801

In [6]:
a = detail_analyze(meandf)

In [7]:
meandf.join(a)

     0           1         2  상위 N% 맛식
0    1  1883770159  2.013472    60.331
1    2    15752650  2.249912     8.911
2    3   714569417  1.971009    70.909
3    4    11385265  1.949141    75.787
4    5   287757696  1.971349    70.830
5    6   392495073  2.263122     7.549
6    7   392495073  1.798023    95.795
7    8    10306127  2.127524    30.369
8    9   434788818  2.218496    12.869
9   10    20638851  1.833683    93.120
10  11  1258680088  2.133357    28.996
11  12    27407049  2.193283    16.825
12  13    27407036  2.136953    28.165
13  14    27407036  1.787889    96.377
14  15   444340519  1.936259    78.439
15  16    14541884  2.087031    40.578
16  17  1566612864  1.770864    97.207
17  18   226916996  1.805411    95.324
18  19   143343585  2.260931     7.763
19  20   880781940  1.937367    78.217
20  21   983114429  1.927943    80.057
21  22    11300334  1.973775    70.261
22  23   746623517  2.117647    32.757
23  24  2020305821  2.172218    20.673
24  25  2020305821  2.175153    20.108
25  26  2020305821  2.147478    25.799
26  27    26353366  2.000697    63.638
27  28  1956466361  1.998232    64.266
28  29  1032781993  1.959879    73.449
29  30  1323716207  1.988070    66.811
30  31   277055458  2.184971    18.285
31  32   777963780  2.292700     5.079
32  33  2084958402  2.100732    37.010
33  34    86660948  2.163929    22.320
34  35  2020305821  2.170801    20.949